window.ALFA_ORIGINAL_DATA = {
  "report": [
    {
      "id": 20,
      "deleted_at": null,
      "admin_id": "12",
      "report_name": "dryfilm",
      "code": "21040601",
      "client_id": "4",
      "is_payer": "1",
      "payer_id": "4",
      "project_id": "21",
      "reviewer_id": "2",
      "date": "2026-07-06",
      "contractor": "Petrojet",
      "sub_contractor": "The Rock",
      "location": "Cairo",
      "tested_item": "Dry film",
      "extra": {
        "guage_name": null,
        "sn": null,
        "tested_items": null,
        "extra_section_title": null
      },
      "test_result": null,
      "created_at": "2026-07-06",
      "updated_at": "2026-07-06T10:35:53.000000Z",
      "status": "<span class='badge badge-warning'>In review</span>",
      "able_to_edit": "0",
      "coating": "&lt;table align=&quot;left&quot; cellspacing=&quot;0&quot; class=&quot;Table&quot; style=&quot;border-collapse:collapse; border:none; margin-left:9px; margin-right:9px; width:6.0in&quot;&gt;\r\n\t&lt;tbody&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;background-color:#e7e6e6; border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; height:15px; vertical-align:top; width:288px&quot;&gt;\r\n\t\t\t&lt;p style=&quot;text-align:justify&quot;&gt;&lt;span style=&quot;font-size:11pt&quot;&gt;&lt;span style=&quot;font-family:&amp;quot;Calibri&amp;quot;,sans-serif&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:black&quot;&gt;Painting Material&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;background-color:#e7e6e6; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:1px solid black; height:15px; vertical-align:top; width:288px&quot;&gt;\r\n\t\t\t&lt;p style=&quot;text-align:justify&quot;&gt;&lt;span style=&quot;font-size:11pt&quot;&gt;&lt;span style=&quot;font-family:&amp;quot;Calibri&amp;quot;,sans-serif&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:black&quot;&gt;Description &lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t&lt;/tbody&gt;\r\n&lt;/table&gt;",
      "extra_section": null,
      "qr": "<div class='symbol symbol-200px me-5'><img src='assets/qr/KD5QFghjj3.png' alt='image' /></div>",
      "report": "Dry Film Thickness",
      "action": "<div class=\"d-flex justify-content-center flex-shrink-0\"><a data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"View\" href=\"#\" class=\"btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1\">\n                    <span class=\"svg-icon svg-icon-3\">\n                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-eye-fill\" viewBox=\"0 0 16 16\">\n                            <path d=\"M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0\"/>\n                            <path d=\"M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7\"/>\n                        </svg>\n                    </span>\n            </a></div>",
      "client": "Xervon",
      "project": "New Heliopolis",
      "created_by": "Ethar Gamal Khamis"
    },
    {
      "id": 19,
      "deleted_at": null,
      "admin_id": "12",
      "report_name": "pulloffadhesion",
      "code": "02020602",
      "client_id": "2",
      "is_payer": "1",
      "payer_id": "2",
      "project_id": "2",
      "reviewer_id": "2",
      "date": "2025-12-15",
      "contractor": "Air Liquide",
      "sub_contractor": "Air Liquide",
      "location": "dg",
      "tested_item": "df",
      "extra": {
        "substrate": "dwf",
        "tested_item_id": "assuit mnha allah",
        "table_of": "5",
        "guage_name": "atm - sn 649",
        "sn": "244",
        "tested_items": "assuit menha",
        "extra_section_title": "asfd"
      },
      "test_result": "&lt;table border=&quot;1&quot; cellpadding=&quot;1&quot; cellspacing=&quot;1&quot; style=&quot;width:500px&quot;&gt;\r\n\t&lt;tbody&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td&gt;&amp;nbsp;&lt;/td&gt;\r\n\t\t\t&lt;td&gt;&amp;nbsp;&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td&gt;&amp;nbsp;&lt;/td&gt;\r\n\t\t\t&lt;td&gt;&amp;nbsp;&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td&gt;&amp;nbsp;&lt;/td&gt;\r\n\t\t\t&lt;td&gt;&amp;nbsp;&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t&lt;/tbody&gt;\r\n&lt;/table&gt;\r\n\r\n&lt;p&gt;&amp;nbsp;&lt;/p&gt;",
      "created_at": "2025-12-15",
      "updated_at": "2025-12-15T10:59:45.000000Z",
      "status": "<span class='badge badge-warning'>In review</span>",
      "able_to_edit": "0",
      "coating": "&lt;table align=&quot;left&quot; cellspacing=&quot;0&quot; class=&quot;Table&quot; style=&quot;border-collapse:collapse; border:none; margin-left:9px; margin-right:9px; width:6.0in&quot;&gt;\r\n\t&lt;tbody&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;background-color:#e7e6e6; border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; height:15px; vertical-align:top; width:288px&quot;&gt;\r\n\t\t\t&lt;p style=&quot;text-align:justify&quot;&gt;&lt;span style=&quot;font-size:11pt&quot;&gt;&lt;span style=&quot;font-family:&amp;quot;Calibri&amp;quot;,sans-serif&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:black&quot;&gt;Painting Material&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;background-color:#e7e6e6; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:1px solid black; height:15px; vertical-align:top; width:288px&quot;&gt;\r\n\t\t\t&lt;p style=&quot;text-align:justify&quot;&gt;&lt;span style=&quot;font-size:11pt&quot;&gt;&lt;span style=&quot;font-family:&amp;quot;Calibri&amp;quot;,sans-serif&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:black&quot;&gt;Description &lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t&lt;/tbody&gt;\r\n&lt;/table&gt;",
      "extra_section": "&lt;p&gt;sdadf&lt;/p&gt;",
      "qr": "<div class='symbol symbol-200px me-5'><img src='assets/qr/iu7fezYxcz.png' alt='image' /></div>",
      "report": "Pull-Off Adhesion Test",
      "action": "<div class=\"d-flex justify-content-center flex-shrink-0\"><a data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"View\" href=\"#\" class=\"btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1\">\n                    <span class=\"svg-icon svg-icon-3\">\n                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-eye-fill\" viewBox=\"0 0 16 16\">\n                            <path d=\"M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0\"/>\n                            <path d=\"M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7\"/>\n                        </svg>\n                    </span>\n            </a></div>",
      "client": "EGC (Engineering Gr)",
      "project": "Sokhna Port",
      "created_by": "Ethar Gamal Khamis"
    },
    {
      "id": 18,
      "deleted_at": null,
      "admin_id": "12",
      "report_name": "pulloffadhesion",
      "code": "03030601",
      "client_id": "3",
      "is_payer": "1",
      "payer_id": "3",
      "project_id": "3",
      "reviewer_id": "2",
      "date": "2025-12-15",
      "contractor": "Xervon",
      "sub_contractor": null,
      "location": "dg",
      "tested_item": "steb",
      "extra": {
        "substrate": "du",
        "tested_item_id": "ei",
        "table_of": "4",
        "guage_name": "atm",
        "sn": "244",
        "tested_items": null,
        "extra_section_title": null
      },
      "test_result": "&lt;p&gt;2e&lt;/p&gt;",
      "created_at": "2025-12-15",
      "updated_at": "2025-12-15T10:42:41.000000Z",
      "status": "<span class='badge badge-warning'>In review</span>",
      "able_to_edit": "0",
      "coating": "&lt;table align=&quot;left&quot; cellspacing=&quot;0&quot; class=&quot;Table&quot; style=&quot;border-collapse:collapse; border:none; margin-left:9px; margin-right:9px; width:6.0in&quot;&gt;\r\n\t&lt;tbody&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;background-color:#e7e6e6; border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; height:15px; vertical-align:top; width:288px&quot;&gt;\r\n\t\t\t&lt;p style=&quot;text-align:justify&quot;&gt;&lt;span style=&quot;font-size:11pt&quot;&gt;&lt;span style=&quot;font-family:&amp;quot;Calibri&amp;quot;,sans-serif&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:black&quot;&gt;Painting Material&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;background-color:#e7e6e6; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:1px solid black; height:15px; vertical-align:top; width:288px&quot;&gt;\r\n\t\t\t&lt;p style=&quot;text-align:justify&quot;&gt;&lt;span style=&quot;font-size:11pt&quot;&gt;&lt;span style=&quot;font-family:&amp;quot;Calibri&amp;quot;,sans-serif&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:black&quot;&gt;Description &lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;h&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;e&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t\t&lt;tr&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t\t&lt;td style=&quot;border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; height:19px; width:288px&quot;&gt;\r\n\t\t\t&lt;p&gt;&amp;nbsp;&lt;/p&gt;\r\n\t\t\t&lt;/td&gt;\r\n\t\t&lt;/tr&gt;\r\n\t&lt;/tbody&gt;\r\n&lt;/table&gt;",
      "extra_section": null,
      "qr": "<div class='symbol symbol-200px me-5'><img src='assets/qr/DgGScANb31.png' alt='image' /></div>",
      "report": "Pull-Off Adhesion Test",
      "action": "<div class=\"d-flex justify-content-center flex-shrink-0\"><a data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"View\" href=\"#\" class=\"btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1\">\n                    <span class=\"svg-icon svg-icon-3\">\n                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-eye-fill\" viewBox=\"0 0 16 16\">\n                            <path d=\"M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0\"/>\n                            <path d=\"M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7\"/>\n                        </svg>\n                    </span>\n            </a></div>",
      "client": "Air Liquide",
      "project": "Iconic Tower",
      "created_by": "Ethar Gamal Khamis"
    }
  ],
  "project": [
    {
      "id": 81,
      "deleted_at": null,
      "title": "test",
      "admin_id": "12",
      "status": "<label class=\"form-check cursor-pointer form-switch form-check-custom form-check-solid justify-content-center\"><input class=\"form-check-input cursor-pointer w-50px switcher\" type=\"checkbox\" data-modelId=\"81\" data-model=\"App\\Models\\Project\" data-columnName=\"status\" checked=\"checked\"></label>",
      "created_at": "2025-12-25",
      "updated_at": "2025-12-25T19:52:22.000000Z",
      "action": "<div class=\"d-flex justify-content-center flex-shrink-0\"><a data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"View\" href=\"#\" class=\"btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1\">\n                    <span class=\"svg-icon svg-icon-3\">\n                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-eye-fill\" viewBox=\"0 0 16 16\">\n                            <path d=\"M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0\"/>\n                            <path d=\"M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7\"/>\n                        </svg>\n                    </span>\n            </a><a data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" title=\"Edit\" href=\"#\" class=\"btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1\">\n                <span class=\"svg-icon svg-icon-3\">\n                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"currentColor\">\n                        <path opacity=\"0.3\" d=\"M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.0825 1.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.9962 6.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.06399 20.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.7934 2.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z\" fill=\"currentColor\"></path>\n                        <path d=\"M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.3789 21.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.696 18.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z\" fill=\"currentColor\"></path>\n                    </svg>\n                </span>\n            </a><a data-bs-toggle=\"modal\" data-bs-target=\"#delete\" href=\"javascript:;\" data-href=\"#\" class=\"btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1\"><span class=\"svg-icon svg-icon-3\">\n                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\">\n                        <path d=\"M5 9C5 8.44772 5.44772 8 6 8H18C18.5523 8 19 8.44772 19 9V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V9Z\" fill=\"currentColor\"></path>\n                        <path opacity=\"0.5\" d=\"M5 5C5 4.44772 5.44772 4 6 4H18C18.5523 4 19 4.44772 19 5V5C19 5.55228 18.5523 6 18 6H6C5.44772 6 5 5.55228 5 5V5Z\" fill=\"currentColor\"></path>\n                        <path opacity=\"0.5\" d=\"M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4V4H9V4Z\" fill=\"currentColor\"></path>\n                    </svg>\n                </span>\n            </a></div>",
      "code": 81,
      "created_by": "Ethar Gamal Khamis"
    }
  ],
  "certificate": [
    {
      "id": "cert-dft-385883",
      "code": "00-15255883",
      "client": "NAT",
      "device": "Coating thickness instrument",
      "serial_no": "385883",
      "manufacturer": "DeFelsko",
      "calibration_date": "26/08/2025",
      "expires_on": "25/08/2026",
      "status": "<span class='badge badge-success'>Valid</span>",
      "created_by": "Malak Khalil",
      "created_at": "2026-06-28",
      "qr": "",
      "action": ""
    },
    {
      "id": "cert-pull-at18752",
      "code": "00-10258752",
      "client": "ASSIUT NATIONAL OIL COMPANY(ANOPC)",
      "device": "PosiTest Adhesion Tester",
      "serial_no": "AT18752",
      "manufacturer": "DeFelsko",
      "calibration_date": "16/08/2025",
      "expires_on": "15/08/2026",
      "status": "<span class='badge badge-success'>Valid</span>",
      "created_by": "Malak Khalil",
      "created_at": "2026-06-14",
      "qr": "",
      "action": ""
    }
  ],
  "client": [
    {
      "id": "1",
      "code": "1",
      "title": "KIT",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "2",
      "code": "2",
      "title": "EGC (Engineering Gr)",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "3",
      "code": "3",
      "title": "Air Liquide",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "4",
      "code": "4",
      "title": "Xervon",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "5",
      "code": "5",
      "title": "ISO Termica",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "6",
      "code": "6",
      "title": "Aresco",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "7",
      "code": "7",
      "title": "SCC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "8",
      "code": "8",
      "title": "DPW",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "9",
      "code": "9",
      "title": "IKK",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "10",
      "code": "10",
      "title": "GS",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "11",
      "code": "11",
      "title": "Tecnimont",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "12",
      "code": "12",
      "title": "DSD",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "13",
      "code": "13",
      "title": "Galfa metal",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "14",
      "code": "14",
      "title": "Sigma Oil",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "15",
      "code": "15",
      "title": "HICC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "16",
      "code": "16",
      "title": "Remasr",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "17",
      "code": "17",
      "title": "Orascom",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "18",
      "code": "18",
      "title": "CIS",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "19",
      "code": "19",
      "title": "Jotun",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "20",
      "code": "20",
      "title": "United Group",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "21",
      "code": "21",
      "title": "Semetar",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "22",
      "code": "22",
      "title": "Fire Trap",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "23",
      "code": "23",
      "title": "Petrojet",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "24",
      "code": "24",
      "title": "El-Sewedy wedy Electric",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "25",
      "code": "25",
      "title": "SHM",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "26",
      "code": "26",
      "title": "Mopco",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "27",
      "code": "27",
      "title": "Technoplast",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "28",
      "code": "28",
      "title": "BPC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "29",
      "code": "29",
      "title": "Total Solution",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "30",
      "code": "30",
      "title": "Energya",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "31",
      "code": "31",
      "title": "Arab Contractors",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "32",
      "code": "32",
      "title": "KIT",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "33",
      "code": "33",
      "title": "ICC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "34",
      "code": "34",
      "title": "Egemech",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "35",
      "code": "35",
      "title": "INPEC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "36",
      "code": "36",
      "title": "NCC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "37",
      "code": "37",
      "title": "Wenspect",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "38",
      "code": "38",
      "title": "Petroplast",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "39",
      "code": "39",
      "title": "Gasco",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "40",
      "code": "40",
      "title": "الاستشارات الهندسية",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "41",
      "code": "41",
      "title": "The Rock",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "42",
      "code": "42",
      "title": "WETCO",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "43",
      "code": "43",
      "title": "NSF",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "44",
      "code": "44",
      "title": "GTS",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "45",
      "code": "45",
      "title": "Mira Tech",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "46",
      "code": "46",
      "title": "Power Steel",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "47",
      "code": "47",
      "title": "Ramec",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "48",
      "code": "48",
      "title": "EG Build",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "49",
      "code": "49",
      "title": "Carlo Gavvasi",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "50",
      "code": "50",
      "title": "Power Market",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "51",
      "code": "51",
      "title": "Petro projects",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "52",
      "code": "52",
      "title": "GCC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "53",
      "code": "53",
      "title": "Aleowad",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "54",
      "code": "54",
      "title": "Kaisd Khair",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "55",
      "code": "55",
      "title": "القناة للموانئ",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "56",
      "code": "56",
      "title": "Archirodon",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "57",
      "code": "57",
      "title": "EDECS",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "58",
      "code": "58",
      "title": "APEX",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "59",
      "code": "59",
      "title": "Saint Gobain",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "60",
      "code": "60",
      "title": "Hassan Allam",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "61",
      "code": "61",
      "title": "Watania Ahmed Zaher",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "62",
      "code": "62",
      "title": "CSCEC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "63",
      "code": "63",
      "title": "SIAC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "64",
      "code": "64",
      "title": "Equal",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "65",
      "code": "65",
      "title": "Master Lab",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "66",
      "code": "66",
      "title": "Core",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "67",
      "code": "67",
      "title": "Tiba",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "68",
      "code": "68",
      "title": "Concord",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "69",
      "code": "69",
      "title": "Kairo Marbel",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "70",
      "code": "70",
      "title": "HDB",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "71",
      "code": "71",
      "title": "Ecobat",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "72",
      "code": "72",
      "title": "Icon",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "73",
      "code": "73",
      "title": "Samco",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "74",
      "code": "74",
      "title": "Makka",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "75",
      "code": "75",
      "title": "Techni build",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "76",
      "code": "76",
      "title": "IAC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "77",
      "code": "77",
      "title": "Mega",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "78",
      "code": "78",
      "title": "AL Amal",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "79",
      "code": "79",
      "title": "Korra",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "80",
      "code": "80",
      "title": "NAT",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "81",
      "code": "81",
      "title": "Novchem",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "82",
      "code": "82",
      "title": "اسكندرية للانشاءات",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "83",
      "code": "83",
      "title": "SA international",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "84",
      "code": "84",
      "title": "EEC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "85",
      "code": "85",
      "title": "Prokem",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "86",
      "code": "86",
      "title": "Sika",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "87",
      "code": "87",
      "title": "Fosroc",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "88",
      "code": "88",
      "title": "Ideal Agencies for Engineering",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "89",
      "code": "89",
      "title": "Araco",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "90",
      "code": "90",
      "title": "Section",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "91",
      "code": "91",
      "title": "Trichem",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "92",
      "code": "92",
      "title": "----",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "93",
      "code": "93",
      "title": "Marvel",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "94",
      "code": "94",
      "title": "Azzar - Reedy Group",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "95",
      "code": "95",
      "title": "Alico",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "96",
      "code": "96",
      "title": "masafee",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "97",
      "code": "97",
      "title": "GCS",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "98",
      "code": "98",
      "title": "China State Construction Engineering Corporation Ltd",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "99",
      "code": "99",
      "title": "ASF",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "100",
      "code": "100",
      "title": "Dynamic Company",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "101",
      "code": "101",
      "title": "Danieli",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "102",
      "code": "102",
      "title": "al salam company for contracting and general supplies",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "103",
      "code": "103",
      "title": "Delmar for Tourism Development",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "104",
      "code": "104",
      "title": "ADNOC",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "105",
      "code": "105",
      "title": "Chengdu design and research institute (CDI)",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "106",
      "code": "106",
      "title": "EL FANAR",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "107",
      "code": "107",
      "title": "EMAAR MISR",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "108",
      "code": "108",
      "title": "EL HAZEK",
      "phone": "",
      "email": "",
      "address": "",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    }
  ],
  "device": [],
  "reviewer": [
    {
      "id": "2",
      "code": "2",
      "title": "Eng. Abdallah Elhamalwy",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "1",
      "code": "1",
      "title": "Eng. Mahmoud Mosaad",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    },
    {
      "id": "3",
      "code": "3",
      "title": "Malak Khalil",
      "created_by": "frontOffice",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "action": ""
    }
  ],
  "staff": [
    {
      "id": "12",
      "code": "12",
      "user_profile_image": "<div class='symbol symbol-50px'><span class='symbol-label bg-light-primary text-primary fw-bold'>FO</span></div>",
      "name": "frontOffice",
      "username": "frontOffice",
      "email": "Omar.Hamalwy@gmail.com",
      "role": "Super admin",
      "role_id": "1",
      "type": "5",
      "position": "Front Office",
      "job_title": "Front Office",
      "password": "Alfa1414$$",
      "daily_rate": "",
      "basic_salary": "",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "updated_at": "",
      "action": ""
    },
    {
      "id": "13",
      "code": "13",
      "user_profile_image": "<div class='symbol symbol-50px'><span class='symbol-label bg-light-info text-info fw-bold'>EG</span></div>",
      "name": "Ethar Gamal Khamis",
      "username": "Ethar Gamal Khamis",
      "email": "",
      "role": "Inspection Engineer",
      "role_id": "5",
      "type": "3",
      "position": "Quality Control",
      "job_title": "Inspection Engineer",
      "password": "Alfa1414$$",
      "daily_rate": "",
      "basic_salary": "",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "updated_at": "",
      "action": ""
    },
    {
      "id": "14",
      "code": "14",
      "user_profile_image": "<div class='symbol symbol-50px'><span class='symbol-label bg-light-warning text-warning fw-bold'>MK</span></div>",
      "name": "Malak Khalil",
      "username": "Malak Khalil",
      "email": "",
      "role": "Inspection Engineer",
      "role_id": "5",
      "type": "3",
      "position": "Quality Control",
      "job_title": "Inspection Engineer",
      "password": "Alfa1414$$",
      "daily_rate": "",
      "basic_salary": "",
      "status": "<span class='badge badge-success'>Active</span>",
      "created_at": "",
      "updated_at": "",
      "action": ""
    }
  ],
  "role": [],
  "quotations": [],
  "conditions": [],
  "assesments": []
};
